"""Euler44_Pentagon numbers
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal
and D = |Pk − Pj| is minimised; what is the value of D?
"""

def main(numTerms):
    pents=[int(n*(3*n-1)/2) for n in range(1,numTerms+1)]
    for j in range(1,numTerms):
        for k in range(j):
            if int(pents[j]-pents[k]) in pents:
                print(pents[j],'and',pents[k],'subtracts to the pent',int(pents[j]-pents[k]))
                if int(pents[j]+pents[k]) in pents:
                     print('******FOUND IT!******')
                     print('and their sum',int(pents[j]+pents[k]),'is also in pents. Answer is:')
                     print(abs(int(pents[j]-pents[k])))
                     return

main(10**5) #will check up through the pent 299,999,000 so might take a while...

"""
(took about an hour to process)
7042750 and 1560090 subtracts to the pent 5482660
******FOUND IT!******
#and their sum 8602840 is also in pents. Answer is: 5482660 #--> CORRECT
    